export const NAV_ROUTES_ADMIN = {
  AUCTION: "AUCTION",
  CASES: "CASES",
  ADMINS: "ADMINS",
  NOTIFICATIONS: "NOTIFICATIONS",
};
export const NAV_ROUTES_SCOUTER = {
  AUCTION: "AUCTION",
  HUNTS: "HUNTS",
  KARMA: "KARMA",
  NOTIFICATIONS: "NOTIFICATIONS",
};
export const NAV_ROUTES_BOOKER = {
  AUCTION: "AUCTION",
  DEALS: "DEALS",
  AGENCY: "AGENCY",
  NOTIFICATIONS: "NOTIFICATIONS",
};
